/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as registerNovicePackageSol from "./Register_novice_package.sol";
export type { registerNovicePackageSol };
import type * as checkIsRegistedSol from "./check_is_registed.sol";
export type { checkIsRegistedSol };
import type * as createCivilizationSol from "./create_civilization.sol";
export type { createCivilizationSol };
export type { Lock } from "./Lock";
