/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as playerdataSol from "./Playerdata.sol";
export type { playerdataSol };
import type * as registerNovicePackageSol from "./Register_novice_package.sol";
export type { registerNovicePackageSol };
import type * as attributeManagementSol from "./attributeManagement.sol";
export type { attributeManagementSol };
import type * as checkIsRegistedSol from "./check_is_registed.sol";
export type { checkIsRegistedSol };
import type * as creatTeamSol from "./creat_team.sol";
export type { creatTeamSol };
import type * as nftTestSol from "./nftTest.sol";
export type { nftTestSol };
export type { Lock } from "./Lock";
