/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumber,
  BigNumberish,
  BytesLike,
  CallOverrides,
  ContractTransaction,
  Overrides,
  PopulatedTransaction,
  Signer,
  utils,
} from "ethers";
import type { FunctionFragment, Result } from "@ethersproject/abi";
import type { Listener, Provider } from "@ethersproject/providers";
import type {
  TypedEventFilter,
  TypedEvent,
  TypedListener,
  OnEvent,
  PromiseOrValue,
} from "../../common";

export interface ManagementInterface extends utils.Interface {
  functions: {
    "Attributelist(address)": FunctionFragment;
    "addAttribute(address,uint256,uint256,uint256,uint256,uint256,uint256,uint256)": FunctionFragment;
    "destroyNft1155(address,uint256)": FunctionFragment;
    "destroyNft721(address,uint256)": FunctionFragment;
  };

  getFunction(
    nameOrSignatureOrTopic:
      | "Attributelist"
      | "addAttribute"
      | "destroyNft1155"
      | "destroyNft721"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "Attributelist",
    values: [PromiseOrValue<string>]
  ): string;
  encodeFunctionData(
    functionFragment: "addAttribute",
    values: [
      PromiseOrValue<string>,
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<BigNumberish>
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "destroyNft1155",
    values: [PromiseOrValue<string>, PromiseOrValue<BigNumberish>]
  ): string;
  encodeFunctionData(
    functionFragment: "destroyNft721",
    values: [PromiseOrValue<string>, PromiseOrValue<BigNumberish>]
  ): string;

  decodeFunctionResult(
    functionFragment: "Attributelist",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "addAttribute",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "destroyNft1155",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "destroyNft721",
    data: BytesLike
  ): Result;

  events: {};
}

export interface Management extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: ManagementInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    Attributelist(
      arg0: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<
      [
        BigNumber,
        BigNumber,
        BigNumber,
        BigNumber,
        BigNumber,
        BigNumber,
        BigNumber
      ] & {
        Stamina: BigNumber;
        Life: BigNumber;
        Strength: BigNumber;
        Intelligence: BigNumber;
        Attack: BigNumber;
        Defense: BigNumber;
        Level: BigNumber;
      }
    >;

    addAttribute(
      Nftcontract: PromiseOrValue<string>,
      Stamina: PromiseOrValue<BigNumberish>,
      Life: PromiseOrValue<BigNumberish>,
      Strength: PromiseOrValue<BigNumberish>,
      Intelligence: PromiseOrValue<BigNumberish>,
      Attack: PromiseOrValue<BigNumberish>,
      Defense: PromiseOrValue<BigNumberish>,
      Level: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    destroyNft1155(
      NftContract: PromiseOrValue<string>,
      tokenId: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    destroyNft721(
      NftContract: PromiseOrValue<string>,
      tokenId: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;
  };

  Attributelist(
    arg0: PromiseOrValue<string>,
    overrides?: CallOverrides
  ): Promise<
    [
      BigNumber,
      BigNumber,
      BigNumber,
      BigNumber,
      BigNumber,
      BigNumber,
      BigNumber
    ] & {
      Stamina: BigNumber;
      Life: BigNumber;
      Strength: BigNumber;
      Intelligence: BigNumber;
      Attack: BigNumber;
      Defense: BigNumber;
      Level: BigNumber;
    }
  >;

  addAttribute(
    Nftcontract: PromiseOrValue<string>,
    Stamina: PromiseOrValue<BigNumberish>,
    Life: PromiseOrValue<BigNumberish>,
    Strength: PromiseOrValue<BigNumberish>,
    Intelligence: PromiseOrValue<BigNumberish>,
    Attack: PromiseOrValue<BigNumberish>,
    Defense: PromiseOrValue<BigNumberish>,
    Level: PromiseOrValue<BigNumberish>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  destroyNft1155(
    NftContract: PromiseOrValue<string>,
    tokenId: PromiseOrValue<BigNumberish>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  destroyNft721(
    NftContract: PromiseOrValue<string>,
    tokenId: PromiseOrValue<BigNumberish>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  callStatic: {
    Attributelist(
      arg0: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<
      [
        BigNumber,
        BigNumber,
        BigNumber,
        BigNumber,
        BigNumber,
        BigNumber,
        BigNumber
      ] & {
        Stamina: BigNumber;
        Life: BigNumber;
        Strength: BigNumber;
        Intelligence: BigNumber;
        Attack: BigNumber;
        Defense: BigNumber;
        Level: BigNumber;
      }
    >;

    addAttribute(
      Nftcontract: PromiseOrValue<string>,
      Stamina: PromiseOrValue<BigNumberish>,
      Life: PromiseOrValue<BigNumberish>,
      Strength: PromiseOrValue<BigNumberish>,
      Intelligence: PromiseOrValue<BigNumberish>,
      Attack: PromiseOrValue<BigNumberish>,
      Defense: PromiseOrValue<BigNumberish>,
      Level: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<void>;

    destroyNft1155(
      NftContract: PromiseOrValue<string>,
      tokenId: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<void>;

    destroyNft721(
      NftContract: PromiseOrValue<string>,
      tokenId: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<void>;
  };

  filters: {};

  estimateGas: {
    Attributelist(
      arg0: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    addAttribute(
      Nftcontract: PromiseOrValue<string>,
      Stamina: PromiseOrValue<BigNumberish>,
      Life: PromiseOrValue<BigNumberish>,
      Strength: PromiseOrValue<BigNumberish>,
      Intelligence: PromiseOrValue<BigNumberish>,
      Attack: PromiseOrValue<BigNumberish>,
      Defense: PromiseOrValue<BigNumberish>,
      Level: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    destroyNft1155(
      NftContract: PromiseOrValue<string>,
      tokenId: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    destroyNft721(
      NftContract: PromiseOrValue<string>,
      tokenId: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    Attributelist(
      arg0: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    addAttribute(
      Nftcontract: PromiseOrValue<string>,
      Stamina: PromiseOrValue<BigNumberish>,
      Life: PromiseOrValue<BigNumberish>,
      Strength: PromiseOrValue<BigNumberish>,
      Intelligence: PromiseOrValue<BigNumberish>,
      Attack: PromiseOrValue<BigNumberish>,
      Defense: PromiseOrValue<BigNumberish>,
      Level: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    destroyNft1155(
      NftContract: PromiseOrValue<string>,
      tokenId: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    destroyNft721(
      NftContract: PromiseOrValue<string>,
      tokenId: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;
  };
}
