/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export * as registerNovicePackageSol from "./Register_novice_package.sol";
export * as checkIsRegistedSol from "./check_is_registed.sol";
export * as createCivilizationSol from "./create_civilization.sol";
export { Lock__factory } from "./Lock__factory";
