/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export * as playerdataSol from "./Playerdata.sol";
export * as registerNovicePackageSol from "./Register_novice_package.sol";
export * as attributeManagementSol from "./attributeManagement.sol";
export * as checkIsRegistedSol from "./check_is_registed.sol";
export * as creatTeamSol from "./creat_team.sol";
export * as nftTestSol from "./nftTest.sol";
export { Lock__factory } from "./Lock__factory";
