/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { ethers } from "ethers";
import {
  FactoryOptions,
  HardhatEthersHelpers as HardhatEthersHelpersBase,
} from "@nomiclabs/hardhat-ethers/types";

import * as Contracts from ".";

declare module "hardhat/types/runtime" {
  interface HardhatEthersHelpers extends HardhatEthersHelpersBase {
    getContractFactory(
      name: "Ownable",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.Ownable__factory>;
    getContractFactory(
      name: "Check_Regist",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.Check_Regist__factory>;
    getContractFactory(
      name: "CreateCivilization",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.CreateCivilization__factory>;
    getContractFactory(
      name: "Lock",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.Lock__factory>;
    getContractFactory(
      name: "RegistContract",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.RegistContract__factory>;

    getContractAt(
      name: "Ownable",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.Ownable>;
    getContractAt(
      name: "Check_Regist",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.Check_Regist>;
    getContractAt(
      name: "CreateCivilization",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.CreateCivilization>;
    getContractAt(
      name: "Lock",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.Lock>;
    getContractAt(
      name: "RegistContract",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.RegistContract>;

    // default types
    getContractFactory(
      name: string,
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<ethers.ContractFactory>;
    getContractFactory(
      abi: any[],
      bytecode: ethers.utils.BytesLike,
      signer?: ethers.Signer
    ): Promise<ethers.ContractFactory>;
    getContractAt(
      nameOrAbi: string | any[],
      address: string,
      signer?: ethers.Signer
    ): Promise<ethers.Contract>;
  }
}
